import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { Readable } from "node:stream";
import { pipeline } from "node:stream/promises";
import test from "node:test";
import type { AsterObjectStorageAdapter, AsterObjectWriteInput } from "@aster/object-storage-s3";
import { ensurePlayableObject } from "../src/infrastructure/fixtures/playable-publisher.js";

const key = "publications/fixture/segment-000.ts";
const bytes = Buffer.from("generated bytes");

function fixture(existing?: Buffer) {
  const signal = new AbortController().signal;
  const calls: string[] = [];
  const writes: AsterObjectWriteInput[] = [];
  let retained = existing;
  const storage: Pick<AsterObjectStorageAdapter, "head" | "read" | "write"> = {
    head(input, active) {
      calls.push("head");
      assert.equal(input.key, key);
      assert.equal(active, signal);
      return Promise.resolve({ status: retained ? "completed" : "not_found" });
    },
    async read(input, active) {
      calls.push("read");
      assert.equal(input.key, key);
      assert.equal(active, signal);
      if (!retained) {
        return { status: "not_found" };
      }
      await pipeline(Readable.from([retained]), input.destination, { signal: active });
      return { status: "completed" };
    },
    async write(input, active) {
      calls.push("write");
      writes.push(input);
      assert.equal(input.key, key);
      assert.equal(active, signal);
      assert.equal(input.ifAbsent, true);
      assert.equal(input.contentLength, bytes.length);
      assert.equal(input.checksumSha256, createHash("sha256").update(bytes).digest("hex"));
      if (retained) {
        return { status: "already_exists" };
      }
      const chunks: Buffer[] = [];
      for await (const chunk of input.source) {
        assert.ok(Buffer.isBuffer(chunk));
        chunks.push(chunk);
      }
      retained = Buffer.concat(chunks);
      return { status: "completed" };
    },
  };
  const run = (publiclyCacheable = true) =>
    ensurePlayableObject(storage, key, bytes, "video/mp2t", signal, publiclyCacheable);
  return { storage, signal, calls, writes, run };
}

test("replay verifies all bytes without a conditional upload or stream rejection", async () => {
  const f = fixture(bytes);
  f.storage.write = () => assert.fail("Existing seed object must not be uploaded again");
  await f.run();
  assert.deepEqual(f.calls, ["head", "read"]);
});

test("missing object is created once with immutable metadata, read back and reused", async () => {
  const f = fixture();
  await f.run();
  await f.run();
  assert.deepEqual(f.calls, ["head", "write", "read", "head", "read"]);
  assert.equal(f.writes.length, 1);
  assert.equal(f.writes[0]?.contentType, "video/mp2t");
  assert.equal(f.writes[0].cacheControl, "public, max-age=31536000, immutable");
  assert.equal(f.writes[0].source.destroyed, true);
});

test("private originals do not receive public cache metadata", async () => {
  const f = fixture();
  await f.run(false);
  assert.equal(f.writes[0]?.cacheControl, undefined);
  assert.deepEqual(f.calls, ["head", "write", "read"]);
});

test("existing mismatched, truncated and oversized bytes reject without replacement", async () => {
  for (const corrupt of [
    Buffer.alloc(bytes.length),
    bytes.subarray(1),
    Buffer.concat([bytes, bytes]),
  ]) {
    const f = fixture(corrupt);
    await assert.rejects(f.run());
    assert.deepEqual(f.calls, ["head", "read"]);
    assert.equal(f.writes.length, 0);
  }
});

test("a creator racing the missing lookup still cannot overwrite or skip readback", async () => {
  for (const retained of [bytes, Buffer.alloc(bytes.length)]) {
    const f = fixture(retained);
    f.storage.head = () => Promise.resolve({ status: "not_found" });
    if (retained === bytes) {
      await f.run();
    } else {
      await assert.rejects(f.run());
    }
    assert.deepEqual(f.calls, ["write", "read"]);
    assert.equal(f.writes[0]?.source.destroyed, true);
  }
});

test("lookup failures never become absence or permit writes", async () => {
  for (const status of ["unavailable", "aborted", "timed_out", "failed"] as const) {
    const f = fixture();
    f.storage.head = () => Promise.resolve({ status });
    await assert.rejects(f.run(), /lookup unavailable/u);
    assert.deepEqual(f.calls, []);
  }
});

test("unknown write results reject without retries or an assumed successful readback", async () => {
  for (const status of ["unavailable", "aborted", "timed_out", "failed"] as const) {
    const f = fixture();
    let source: Readable | undefined;
    f.storage.write = (input) => {
      source = input.source;
      return Promise.resolve({ status });
    };
    await assert.rejects(f.run(), /upload unavailable/u);
    assert.equal(source?.destroyed, true);
    assert.deepEqual(f.calls, ["head"]);
  }
});

test("an object disappearing or becoming unreadable after lookup is not repaired", async () => {
  for (const status of ["not_found", "unavailable", "timed_out", "aborted"] as const) {
    const f = fixture(bytes);
    f.storage.read = () => Promise.resolve({ status });
    await assert.rejects(f.run(), /readback mismatch/u);
    assert.deepEqual(f.calls, ["head"]);
    assert.equal(f.writes.length, 0);
  }
});

test("cancellation before or during lookup prevents further work", async () => {
  const f = fixture();
  await assert.rejects(
    ensurePlayableObject(f.storage, key, bytes, "video/mp2t", AbortSignal.abort()),
  );
  assert.deepEqual(f.calls, []);
  const controller = new AbortController();
  f.storage.head = (_input, active) => {
    assert.equal(active, controller.signal);
    controller.abort();
    return Promise.resolve({ status: "not_found" });
  };
  await assert.rejects(
    ensurePlayableObject(f.storage, key, bytes, "video/mp2t", controller.signal),
  );
  assert.deepEqual(f.calls, []);
});
