apiVersion: 1

datasources:
  - name: Aster Tempo
    uid: aster-tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    editable: false
    jsonData:
      httpMethod: GET
      nodeGraph:
        enabled: true
      tracesToMetrics:
        datasourceUid: aster-prometheus
        spanStartTimeShift: -1m
        spanEndTimeShift: 1m
        queries:
          - name: Dependency outcomes
            query: sum by (aster_dependency, aster_operation, aster_outcome) (rate(aster_dependency_operation_outcomes_total[5m]))
