apiVersion: 1

deleteDatasources:
  - name: Aster Prometheus
    orgId: 1

datasources:
  - name: Aster Prometheus
    uid: aster-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    orgId: 1
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      manageAlerts: false
      prometheusType: Prometheus
      prometheusVersion: 3.14.0
      timeInterval: 5s
